name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: food_demand
  ACR_NAME: aitprojectsregistry
  CONTAINERAPP_NAME: food-demand
  RESOURCE_GROUP: containers
  REGION: southeastasia

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login
        run: |
          echo "Logging into Azure..."
          az login --service-principal \
            --username "${{ secrets.AZURE_CLIENT_ID }}" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

          echo "Setting Azure subscription..."
          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Confirm access
        run: az account show

      - name: Log in to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          ACR_LOGIN_SERVER=$(az acr show --name ${{ env.ACR_NAME }} --query loginServer -o tsv)
          docker build -t $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:$IMAGE_TAG ./app_v3
          docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:$IMAGE_TAG
          echo "IMAGE_URI=$ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Deploy to Azure Container App
        run: |
          echo "Updating Container App to new image..."
          az containerapp update \
            --name ${{ env.CONTAINERAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.IMAGE_URI }}
