name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - main # change if you use a different branch
      - beta
  workflow_dispatch:

env:
  IMAGE_NAME: food_demand_app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Azure using service principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry
      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # Build and push Docker image to ACR
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          ACR_LOGIN_SERVER=$(az acr show --name ${{ secrets.ACR_NAME }} --query "loginServer" -o tsv)
          docker build -t $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:$IMAGE_TAG ./app_v3
          docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:$IMAGE_TAG
          echo "IMAGE_URI=$ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:$IMAGE_TAG" >> $GITHUB_ENV

      # Deploy to Azure Container App
      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINERAPP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image $IMAGE_URI
